import React from 'react';
import { useNavigate } from 'react-router-dom';

const sectionTitle = {
  fontWeight: 700,
  fontSize: '1.3rem',
  color: '#2c5e57',
  marginTop: '2em',
  marginBottom: '0.5em'
};

const bold = { fontWeight: 700 };

const PrivacyPolicy = () => {
  const navigate = useNavigate();

  const handleBack = () => {
    // Go back to previous page, or to home if no previous page
    if (window.history.length > 1) {
      navigate(-1);
    } else {
      navigate('/');
    }
  };

  return (
    <div style={{
      maxWidth: 900,
      margin: '40px auto',
      padding: '32px',
      background: '#fff',
      borderRadius: 12,
      fontFamily: 'Karma, serif',
      color: '#222'
    }}>
      {/* Back Button */}
      <button
        onClick={handleBack}
        style={{
          background: '#2c5e57',
          color: 'white',
          border: 'none',
          padding: '12px 24px',
          borderRadius: '6px',
          cursor: 'pointer',
          fontSize: '16px',
          fontWeight: 600,
          marginBottom: '24px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          transition: 'background-color 0.2s ease'
        }}
        onMouseOver={(e) => e.target.style.backgroundColor = '#1e4a44'}
        onMouseOut={(e) => e.target.style.backgroundColor = '#2c5e57'}
      >
        ← Back
      </button>

      <h1 style={{ fontFamily: 'Jockey One, Arial, sans-serif', color: '#2c5e57', fontWeight: 900, fontSize: '2.5rem' }}>Privacy Policy</h1>

      <h2 style={sectionTitle}>I. Introduction</h2>
      <p>
        Welcome to Guan Yiac Hardware<br /><br />
        Guan Yiac Hardware ("us", "we", or "our") operates guanyiac.com (hereinafter referred to as "Service").<br /><br />
        Our Privacy Policy governs your visit to guanyiac.com and explains how we collect, safeguard and disclose information that results from your use of our Service.<br /><br />
        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.<br /><br />
        Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
      </p>

      <h2 style={sectionTitle}>II. Definitions</h2>
      <p>
        <span style={bold}>SERVICE</span> means the guanyiac.com website operated by Guan Yiac Hardware.<br /><br />
        <span style={bold}>PERSONAL DATA</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br /><br />
        <span style={bold}>USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).<br /><br />
        <span style={bold}>COOKIES</span> are small files stored on your device (computer or mobile device).<br /><br />
        <span style={bold}>DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br /><br />
        <span style={bold}>DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br /><br />
        <span style={bold}>DATA SUBJECT</span> is any living individual who is the subject of Personal Data.<br /><br />
        <span style={bold}>THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
      </p>

      <h2 style={sectionTitle}>III. Information Collection and Use</h2>
      <p>
        We collect several different types of information for various purposes to provide and improve our Service to you.
      </p>

      <h2 style={sectionTitle}>IV. Types of Data Collected</h2>
      <h3 style={{ fontWeight: 600, color: '#2c5e57', marginTop: '1.5em' }}>Personal Data</h3>
      <p>
        While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
      </p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>Email Address</li>
        <li>First name and Last name</li>
        <li>Phone Number</li>
        <li>Address, Country, Province, ZIP/Postal Code, City</li>
        <li>Cookies and Usage Data</li>
      </ul>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
      </p>

      <h3 style={{ fontWeight: 600, color: '#2c5e57', marginTop: '1.5em' }}>Usage Data</h3>
      <p>
        We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>

      <h3 style={{ fontWeight: 600, color: '#2c5e57', marginTop: '1.5em' }}>Tracking & Cookies Data</h3>
      <p>
        We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.<br /><br />
        Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.<br /><br />
        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
      </p>

      <h2 style={sectionTitle}>V. Use of Data</h2>
      <p>Guan Yiac Hardware uses the collected data for various purposes:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>To provide and maintain the Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
        <li>To provide customer care and support</li>
        <li>To provide analysis or valuable information so that we can improve the Service</li>
        <li>To monitor the usage of the Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>To fulfill any other purpose for which you provide it</li>
        <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection</li>
        <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.</li>
        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
        <li>In any other way we may describe when you provide the information</li>
        <li>For any other purpose with your consent</li>
      </ul>

      <h2 style={sectionTitle}>VI. Retention of Data</h2>
      <p>
        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br /><br />
        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
      </p>

      <h2 style={sectionTitle}>VII. Transfer of Data</h2>
      <p>
        Your information, including Personal Data, is transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.<br /><br />
        If you are located outside Philippines and choose to provide information to us, please note that we transfer the data, including Personal Data, to Philippines and process it there.<br /><br />
        Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br /><br />
        Guan Yiac Hardware will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
      </p>

      <h2 style={sectionTitle}>VIII. Disclosure of Data</h2>
      <p>We may disclose personal information that we collect, or you provide:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li><span style={bold}>Disclosure for Law Enforcement.</span> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
        <li><span style={bold}>Business Transaction.</span> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
        <li><span style={bold}>Other cases. We may disclose your information also:</span>
          <ul style={{ marginLeft: '2em', marginTop: '0.5em' }}>
            <li>to our subsidiaries and affiliates;</li>
            <li>to contractors, service providers, and other third parties we use to support our business;</li>
            <li>to fulfill the purpose for which you provide it;</li>
            <li>for the purpose of including your company's logo on our website;</li>
            <li>for any other purpose disclosed by us when you provide the information;</li>
            <li>with your consent in any other cases;</li>
            <li>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
          </ul>
        </li>
      </ul>

      <h2 style={sectionTitle}>IX. Security of Data</h2>
      <p>
        The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h2 style={sectionTitle}>X. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
      <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Guan Yiac Hardware aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
      <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us.</p>
      <p>In certain circumstances, you have the following data protection rights:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>The right to access, update or to delete the information we have on you;</li>
        <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
        <li>The right to object. You have the right to object to our processing of your Personal Data;</li>
        <li>The right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
        <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
        <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where Guan Yiac Hardware relied on your consent to process your personal information;</li>
      </ul>
      <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
      <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

      <h2 style={sectionTitle}>XI. Your Data Protection Rights under the Privacy Act 1988 (Cth)</h2>
      <p>If you are an Australian resident, you have certain data protection rights. Guan Yiac Hardware aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
      <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us.</p>
      <p>In certain circumstances, you have the following data protection rights:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>The right to access, update or to delete the information we have on you;</li>
        <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
        <li>The right to object. You have the right to object to our processing of your Personal Data;</li>
        <li>The right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
        <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
        <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where Guan Yiac Hardware relied on your consent to process your personal information;</li>
      </ul>
      <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
      <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in Australia.</p>

      <h2 style={sectionTitle}>XII. Service Providers</h2>
      <p>We may employ third party companies and individuals due to the following reasons:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>To facilitate our Service;</li>
        <li>To provide the Service on our behalf;</li>
        <li>To perform Service-related services; or</li>
        <li>To assist us in analyzing how our Service is used.</li>
      </ul>
      <p>We want to inform our Service users that these third parties have access to your Personal Data. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</p>

      <h2 style={sectionTitle}>XIII. Analytics</h2>
      <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

      <h2 style={sectionTitle}>XIV. CI/CD tools</h2>
      <p>We may use third-party Service Providers to automate the development process of our Service.</p>

      <h2 style={sectionTitle}>XV. Behavioral Remarketing</h2>
      <p>Guan Yiac Hardware uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>

      <h2 style={sectionTitle}>XVI. Links to Other Sites</h2>
      <p>
        Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.<br /><br />
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
      </p>

      <h2 style={sectionTitle}>XVII. Children's Privacy</h2>
      <p>
        Our Services are not intended for use by children under the age of 18 ("Child" or "Children").<br /><br />
        We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
      </p>

      <h2 style={sectionTitle}>XVIII. Changes to This Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br /><br />
        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.<br /><br />
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </p>

      <h2 style={sectionTitle}>XIX. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, please contact us:</p>
      <ul style={{ marginLeft: '2em', lineHeight: '1.8' }}>
        <li>By email: info@guanyiac.com.ph</li>
        <li>By visiting this page on our website: guanyiac.com.ph</li>
        <li>By phone number: +63 2 8 123 4567</li>
        <li>By mail: 123 Main Street, Quezon City, Metro Manila, Philippines</li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;